### ISSUE TITLE
Site mort :(

### ISSUE THREAD

**Issue by Kocal** [turion64guy/Sndbobweb#1]
Nom de domaine mort ... :sob:

**Comment by turion64guy** [comment]
Merci, je sais, j'ai perdu mon nom de domaine jusqu'à 2028... En attendant
j'ai réservé 3 autres domaines.
Tu peux remplacer "turion64.cf" par "turion64.ml" ou carrément l'adresse IP
"88.170.73.166"

Le lun. 12 mars 2018 à 14:45, Hugo Alliaume <notifications@github.com> a
écrit :

**Comment by turion64guy** [comment]
Voilà, j'ai changé l'URL du site sur le git.
Tu peux y accéder sur : http://turion64.ml/soundbox/
(Ou http://88.170.73.166/soundbox/ si jamais le domaine expire encore)

**Comment by Kocal** [comment]
Arf, okay tant mieux que tu sois déjà au courant, je pensais que c'était arrivé ce matin... :disappointed: 

Nickel, merci pour les nouveaux liens !! :smile:

**Comment by turion64guy** [comment]
L'expiration est arrivée vendredi il me semble.
Merci, j'aurais jamais pensé à modifier les liens sur mon github.
